// "use client";

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { useState } from "react";
// import Sidebar from "./components/Sidebar";
// import Topbar from "./components/Topbar";
// import ReduxProvider from "@/redux/provider";
// import { useAppSelector } from "@/redux/hooks";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//    const [collapsed, setCollapsed] = useState(false);
//   const [mobileOpen, setMobileOpen] = useState(false);
  
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body suppressHydrationWarning >
//         <ReduxProvider>
//         <div  className="min-h-full flex flex-col">
//           <Topbar setMobileOpen={setMobileOpen} />
//           <div className="flex h-screen ">
//       {/* Sidebar Desktop */}
//       <Sidebar
//         collapsed={collapsed}
//         setCollapsed={setCollapsed}
//         mobileOpen={mobileOpen}
//         setMobileOpen={setMobileOpen}
//       />

//       {/* Main Content */}
//       <div className="flex-1 flex flex-col">
      

//         <main className="p-4 overflow-y-auto">{children}</main>
//       </div>
//     </div>
//         </div>
//         </ReduxProvider>
//         </body>
//     </html>
//   );
// }


// app/layout.tsx

import ReduxProvider from "@/redux/provider";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import AuthInitializer from "./components/AuthInitializer";
// import ClientLayout from "./ClientLayout";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body  className="h-full ">
        <ReduxProvider>
          <AuthInitializer>
          <ClientLayout>{children}</ClientLayout>
          </AuthInitializer>
        </ReduxProvider>
      </body>
    </html>
  );
}
