import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import UserInitializer from "@/components/providers/UserInitializer";
import ReduxProvider from "@/redux/provider";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
       <ReduxProvider>
          <UserInitializer  />
          {children}
    </ReduxProvider>
      </body>
    </html>
  );
}